/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = PlantCreatedPayload.Builder.class
)
public final class PlantCreatedPayload {
  private final Optional<PlantCreatedPayloadEvent> event;

  private final Optional<OffsetDateTime> timestamp;

  private final Optional<PlantResponse> data;

  private final Map<String, Object> additionalProperties;

  private PlantCreatedPayload(Optional<PlantCreatedPayloadEvent> event,
      Optional<OffsetDateTime> timestamp, Optional<PlantResponse> data,
      Map<String, Object> additionalProperties) {
    this.event = event;
    this.timestamp = timestamp;
    this.data = data;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("event")
  public Optional<PlantCreatedPayloadEvent> getEvent() {
    return event;
  }

  @JsonProperty("timestamp")
  public Optional<OffsetDateTime> getTimestamp() {
    return timestamp;
  }

  @JsonProperty("data")
  public Optional<PlantResponse> getData() {
    return data;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof PlantCreatedPayload && equalTo((PlantCreatedPayload) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(PlantCreatedPayload other) {
    return event.equals(other.event) && timestamp.equals(other.timestamp) && data.equals(other.data);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.event, this.timestamp, this.data);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<PlantCreatedPayloadEvent> event = Optional.empty();

    private Optional<OffsetDateTime> timestamp = Optional.empty();

    private Optional<PlantResponse> data = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(PlantCreatedPayload other) {
      event(other.getEvent());
      timestamp(other.getTimestamp());
      data(other.getData());
      return this;
    }

    @JsonSetter(
        value = "event",
        nulls = Nulls.SKIP
    )
    public Builder event(Optional<PlantCreatedPayloadEvent> event) {
      this.event = event;
      return this;
    }

    public Builder event(PlantCreatedPayloadEvent event) {
      this.event = Optional.ofNullable(event);
      return this;
    }

    @JsonSetter(
        value = "timestamp",
        nulls = Nulls.SKIP
    )
    public Builder timestamp(Optional<OffsetDateTime> timestamp) {
      this.timestamp = timestamp;
      return this;
    }

    public Builder timestamp(OffsetDateTime timestamp) {
      this.timestamp = Optional.ofNullable(timestamp);
      return this;
    }

    @JsonSetter(
        value = "data",
        nulls = Nulls.SKIP
    )
    public Builder data(Optional<PlantResponse> data) {
      this.data = data;
      return this;
    }

    public Builder data(PlantResponse data) {
      this.data = Optional.ofNullable(data);
      return this;
    }

    public PlantCreatedPayload build() {
      return new PlantCreatedPayload(event, timestamp, data, additionalProperties);
    }
  }
}
