/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class PlantCreatedPayloadEvent {
  public static final PlantCreatedPayloadEvent PLANT_CREATED = new PlantCreatedPayloadEvent(Value.PLANT_CREATED, "plant.created");

  private final Value value;

  private final String string;

  PlantCreatedPayloadEvent(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof PlantCreatedPayloadEvent && this.string.equals(((PlantCreatedPayloadEvent) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case PLANT_CREATED:
        return visitor.visitPlantCreated();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static PlantCreatedPayloadEvent valueOf(String value) {
    switch (value) {
      case "plant.created":
        return PLANT_CREATED;
      default:
        return new PlantCreatedPayloadEvent(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    PLANT_CREATED,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitPlantCreated();

    T visitUnknown(String unknownType);
  }
}
