/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class PostPlantUpdatedPayloadEvent {
  public static final PostPlantUpdatedPayloadEvent PLANT_UPDATED = new PostPlantUpdatedPayloadEvent(Value.PLANT_UPDATED, "plant.updated");

  private final Value value;

  private final String string;

  PostPlantUpdatedPayloadEvent(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof PostPlantUpdatedPayloadEvent && this.string.equals(((PostPlantUpdatedPayloadEvent) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case PLANT_UPDATED:
        return visitor.visitPlantUpdated();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static PostPlantUpdatedPayloadEvent valueOf(String value) {
    switch (value) {
      case "plant.updated":
        return PLANT_UPDATED;
      default:
        return new PostPlantUpdatedPayloadEvent(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    PLANT_UPDATED,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitPlantUpdated();

    T visitUnknown(String unknownType);
  }
}
