/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class WebhookRegistrationEventsItem {
  public static final WebhookRegistrationEventsItem PLANT_UPDATED = new WebhookRegistrationEventsItem(Value.PLANT_UPDATED, "plant.updated");

  public static final WebhookRegistrationEventsItem PLANT_STATUS_CHANGED = new WebhookRegistrationEventsItem(Value.PLANT_STATUS_CHANGED, "plant.status_changed");

  public static final WebhookRegistrationEventsItem PLANT_DELETED = new WebhookRegistrationEventsItem(Value.PLANT_DELETED, "plant.deleted");

  public static final WebhookRegistrationEventsItem PLANT_CREATED = new WebhookRegistrationEventsItem(Value.PLANT_CREATED, "plant.created");

  private final Value value;

  private final String string;

  WebhookRegistrationEventsItem(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof WebhookRegistrationEventsItem && this.string.equals(((WebhookRegistrationEventsItem) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case PLANT_UPDATED:
        return visitor.visitPlantUpdated();
      case PLANT_STATUS_CHANGED:
        return visitor.visitPlantStatusChanged();
      case PLANT_DELETED:
        return visitor.visitPlantDeleted();
      case PLANT_CREATED:
        return visitor.visitPlantCreated();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static WebhookRegistrationEventsItem valueOf(String value) {
    switch (value) {
      case "plant.updated":
        return PLANT_UPDATED;
      case "plant.status_changed":
        return PLANT_STATUS_CHANGED;
      case "plant.deleted":
        return PLANT_DELETED;
      case "plant.created":
        return PLANT_CREATED;
      default:
        return new WebhookRegistrationEventsItem(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    PLANT_CREATED,

    PLANT_UPDATED,

    PLANT_STATUS_CHANGED,

    PLANT_DELETED,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitPlantCreated();

    T visitPlantUpdated();

    T visitPlantStatusChanged();

    T visitPlantDeleted();

    T visitUnknown(String unknownType);
  }
}
