/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = WebhookRegistration.Builder.class
)
public final class WebhookRegistration {
  private final String url;

  private final List<WebhookRegistrationEventsItem> events;

  private final Optional<String> secret;

  private final Map<String, Object> additionalProperties;

  private WebhookRegistration(String url, List<WebhookRegistrationEventsItem> events,
      Optional<String> secret, Map<String, Object> additionalProperties) {
    this.url = url;
    this.events = events;
    this.secret = secret;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The URL where webhook events will be sent
   */
  @JsonProperty("url")
  public String getUrl() {
    return url;
  }

  /**
   * @return List of events to subscribe to
   */
  @JsonProperty("events")
  public List<WebhookRegistrationEventsItem> getEvents() {
    return events;
  }

  /**
   * @return Secret used to sign webhook payloads
   */
  @JsonProperty("secret")
  public Optional<String> getSecret() {
    return secret;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof WebhookRegistration && equalTo((WebhookRegistration) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(WebhookRegistration other) {
    return url.equals(other.url) && events.equals(other.events) && secret.equals(other.secret);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.url, this.events, this.secret);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static UrlStage builder() {
    return new Builder();
  }

  public interface UrlStage {
    /**
     * <p>The URL where webhook events will be sent</p>
     */
    _FinalStage url(@NotNull String url);

    Builder from(WebhookRegistration other);
  }

  public interface _FinalStage {
    WebhookRegistration build();

    /**
     * <p>List of events to subscribe to</p>
     */
    _FinalStage events(List<WebhookRegistrationEventsItem> events);

    _FinalStage addEvents(WebhookRegistrationEventsItem events);

    _FinalStage addAllEvents(List<WebhookRegistrationEventsItem> events);

    /**
     * <p>Secret used to sign webhook payloads</p>
     */
    _FinalStage secret(Optional<String> secret);

    _FinalStage secret(String secret);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements UrlStage, _FinalStage {
    private String url;

    private Optional<String> secret = Optional.empty();

    private List<WebhookRegistrationEventsItem> events = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(WebhookRegistration other) {
      url(other.getUrl());
      events(other.getEvents());
      secret(other.getSecret());
      return this;
    }

    /**
     * <p>The URL where webhook events will be sent</p>
     * <p>The URL where webhook events will be sent</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("url")
    public _FinalStage url(@NotNull String url) {
      this.url = Objects.requireNonNull(url, "url must not be null");
      return this;
    }

    /**
     * <p>Secret used to sign webhook payloads</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage secret(String secret) {
      this.secret = Optional.ofNullable(secret);
      return this;
    }

    /**
     * <p>Secret used to sign webhook payloads</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "secret",
        nulls = Nulls.SKIP
    )
    public _FinalStage secret(Optional<String> secret) {
      this.secret = secret;
      return this;
    }

    /**
     * <p>List of events to subscribe to</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addAllEvents(List<WebhookRegistrationEventsItem> events) {
      if (events != null) {
        this.events.addAll(events);
      }
      return this;
    }

    /**
     * <p>List of events to subscribe to</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addEvents(WebhookRegistrationEventsItem events) {
      this.events.add(events);
      return this;
    }

    /**
     * <p>List of events to subscribe to</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "events",
        nulls = Nulls.SKIP
    )
    public _FinalStage events(List<WebhookRegistrationEventsItem> events) {
      this.events.clear();
      if (events != null) {
        this.events.addAll(events);
      }
      return this;
    }

    @java.lang.Override
    public WebhookRegistration build() {
      return new WebhookRegistration(url, events, secret, additionalProperties);
    }
  }
}
