/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class WebhookResponseStatus {
  public static final WebhookResponseStatus INACTIVE = new WebhookResponseStatus(Value.INACTIVE, "inactive");

  public static final WebhookResponseStatus ACTIVE = new WebhookResponseStatus(Value.ACTIVE, "active");

  private final Value value;

  private final String string;

  WebhookResponseStatus(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof WebhookResponseStatus && this.string.equals(((WebhookResponseStatus) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case INACTIVE:
        return visitor.visitInactive();
      case ACTIVE:
        return visitor.visitActive();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static WebhookResponseStatus valueOf(String value) {
    switch (value) {
      case "inactive":
        return INACTIVE;
      case "active":
        return ACTIVE;
      default:
        return new WebhookResponseStatus(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    ACTIVE,

    INACTIVE,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitActive();

    T visitInactive();

    T visitUnknown(String unknownType);
  }
}
