/**
 * This file was auto-generated by Fern from our API Definition.
 */

package types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = WebhookResponse.Builder.class
)
public final class WebhookResponse {
  private final Optional<String> id;

  private final Optional<String> url;

  private final Optional<List<String>> events;

  private final Optional<WebhookResponseStatus> status;

  private final Map<String, Object> additionalProperties;

  private WebhookResponse(Optional<String> id, Optional<String> url, Optional<List<String>> events,
      Optional<WebhookResponseStatus> status, Map<String, Object> additionalProperties) {
    this.id = id;
    this.url = url;
    this.events = events;
    this.status = status;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Unique identifier for the webhook
   */
  @JsonProperty("id")
  public Optional<String> getId() {
    return id;
  }

  /**
   * @return The URL where webhook events are sent
   */
  @JsonProperty("url")
  public Optional<String> getUrl() {
    return url;
  }

  /**
   * @return List of subscribed events
   */
  @JsonProperty("events")
  public Optional<List<String>> getEvents() {
    return events;
  }

  /**
   * @return Current status of the webhook
   */
  @JsonProperty("status")
  public Optional<WebhookResponseStatus> getStatus() {
    return status;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof WebhookResponse && equalTo((WebhookResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(WebhookResponse other) {
    return id.equals(other.id) && url.equals(other.url) && events.equals(other.events) && status.equals(other.status);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.url, this.events, this.status);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> id = Optional.empty();

    private Optional<String> url = Optional.empty();

    private Optional<List<String>> events = Optional.empty();

    private Optional<WebhookResponseStatus> status = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(WebhookResponse other) {
      id(other.getId());
      url(other.getUrl());
      events(other.getEvents());
      status(other.getStatus());
      return this;
    }

    /**
     * <p>Unique identifier for the webhook</p>
     */
    @JsonSetter(
        value = "id",
        nulls = Nulls.SKIP
    )
    public Builder id(Optional<String> id) {
      this.id = id;
      return this;
    }

    public Builder id(String id) {
      this.id = Optional.ofNullable(id);
      return this;
    }

    /**
     * <p>The URL where webhook events are sent</p>
     */
    @JsonSetter(
        value = "url",
        nulls = Nulls.SKIP
    )
    public Builder url(Optional<String> url) {
      this.url = url;
      return this;
    }

    public Builder url(String url) {
      this.url = Optional.ofNullable(url);
      return this;
    }

    /**
     * <p>List of subscribed events</p>
     */
    @JsonSetter(
        value = "events",
        nulls = Nulls.SKIP
    )
    public Builder events(Optional<List<String>> events) {
      this.events = events;
      return this;
    }

    public Builder events(List<String> events) {
      this.events = Optional.ofNullable(events);
      return this;
    }

    /**
     * <p>Current status of the webhook</p>
     */
    @JsonSetter(
        value = "status",
        nulls = Nulls.SKIP
    )
    public Builder status(Optional<WebhookResponseStatus> status) {
      this.status = status;
      return this;
    }

    public Builder status(WebhookResponseStatus status) {
      this.status = Optional.ofNullable(status);
      return this;
    }

    public WebhookResponse build() {
      return new WebhookResponse(id, url, events, status, additionalProperties);
    }
  }
}
