// Code generated by Fern. DO NOT EDIT.

package plant

import (
	context "context"
	sdk "sdk"
	core "sdk/core"
	internal "sdk/internal"
	option "sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (c *Client) AddPlant(
	ctx context.Context,
	request *sdk.Plant,
	opts ...option.RequestOption,
) (*sdk.PlantResponse, error) {
	response, err := c.WithRawResponse.AddPlant(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) UpdatePlant(
	ctx context.Context,
	request *sdk.Plant,
	opts ...option.RequestOption,
) (*sdk.PlantResponse, error) {
	response, err := c.WithRawResponse.UpdatePlant(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Filter plants based on their current status.
func (c *Client) SearchPlantsByStatus(
	ctx context.Context,
	request *sdk.SearchPlantsByStatusRequest,
	opts ...option.RequestOption,
) ([]*sdk.PlantResponse, error) {
	response, err := c.WithRawResponse.SearchPlantsByStatus(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Filter plants based on associated tags.
func (c *Client) SearchPlantsByTags(
	ctx context.Context,
	request *sdk.SearchPlantsByTagsRequest,
	opts ...option.RequestOption,
) ([]*sdk.PlantResponse, error) {
	response, err := c.WithRawResponse.SearchPlantsByTags(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve a plant's details by its ID.
func (c *Client) GetPlantById(
	ctx context.Context,
	request *sdk.GetPlantByIdRequest,
	opts ...option.RequestOption,
) (*sdk.PlantResponse, error) {
	response, err := c.WithRawResponse.GetPlantById(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
