// This file was auto-generated by Fern from our API Definition.

import type * as JustinDouvilleApi from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface SearchPlantsByStatusRequest {
    /** The status of plants to search for. */
    status?: JustinDouvilleApi.SearchPlantsByStatusRequestStatus;
}
