// Code generated by Fern. DO NOT EDIT.

package client

import (
	core "sdk/core"
	internal "sdk/internal"
	option "sdk/option"
	plant "sdk/plant"
	user "sdk/user"
)

type Client struct {
	Plant *plant.Client
	User  *user.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		Plant:   plant.NewClient(options),
		User:    user.NewClient(options),
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}
