# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        Plant,
        PlantCreatedPayload,
        PlantCreatedPayloadEvent,
        PlantResponse,
        PlantStatus,
        PostPlantUpdatedPayload,
        PostPlantUpdatedPayloadEvent,
        User,
        UserAuthResponse,
        WebhookRegistration,
        WebhookRegistrationEventsItem,
        WebhookResponse,
        WebhookResponseStatus,
    )
    from .errors import BadRequestError, MethodNotAllowedError, NotFoundError
    from . import plant, user
    from .client import AsyncJustinDouvilleApi, JustinDouvilleApi
    from .environment import JustinDouvilleApiEnvironment
    from .plant import SearchPlantsByStatusRequestStatus
_dynamic_imports: typing.Dict[str, str] = {
    "AsyncJustinDouvilleApi": ".client",
    "BadRequestError": ".errors",
    "JustinDouvilleApi": ".client",
    "JustinDouvilleApiEnvironment": ".environment",
    "MethodNotAllowedError": ".errors",
    "NotFoundError": ".errors",
    "Plant": ".types",
    "PlantCreatedPayload": ".types",
    "PlantCreatedPayloadEvent": ".types",
    "PlantResponse": ".types",
    "PlantStatus": ".types",
    "PostPlantUpdatedPayload": ".types",
    "PostPlantUpdatedPayloadEvent": ".types",
    "SearchPlantsByStatusRequestStatus": ".plant",
    "User": ".types",
    "UserAuthResponse": ".types",
    "WebhookRegistration": ".types",
    "WebhookRegistrationEventsItem": ".types",
    "WebhookResponse": ".types",
    "WebhookResponseStatus": ".types",
    "plant": ".plant",
    "user": ".user",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AsyncJustinDouvilleApi",
    "BadRequestError",
    "JustinDouvilleApi",
    "JustinDouvilleApiEnvironment",
    "MethodNotAllowedError",
    "NotFoundError",
    "Plant",
    "PlantCreatedPayload",
    "PlantCreatedPayloadEvent",
    "PlantResponse",
    "PlantStatus",
    "PostPlantUpdatedPayload",
    "PostPlantUpdatedPayloadEvent",
    "SearchPlantsByStatusRequestStatus",
    "User",
    "UserAuthResponse",
    "WebhookRegistration",
    "WebhookRegistrationEventsItem",
    "WebhookResponse",
    "WebhookResponseStatus",
    "plant",
    "user",
]
