// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import type * as JustinDouvilleApi from "../../../index.js";

export declare namespace UserClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Operations about user
 */
export class UserClient {
    protected readonly _options: NormalizedClientOptions<UserClient.Options>;

    constructor(options: UserClient.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * @param {JustinDouvilleApi.LoginUserRequest} request
     * @param {UserClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.user.loginUser()
     */
    public loginUser(
        request: JustinDouvilleApi.LoginUserRequest = {},
        requestOptions?: UserClient.RequestOptions,
    ): core.HttpResponsePromise<JustinDouvilleApi.UserAuthResponse> {
        return core.HttpResponsePromise.fromPromise(this.__loginUser(request, requestOptions));
    }

    private async __loginUser(
        request: JustinDouvilleApi.LoginUserRequest = {},
        requestOptions?: UserClient.RequestOptions,
    ): Promise<core.WithRawResponse<JustinDouvilleApi.UserAuthResponse>> {
        const { username, password } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (username != null) {
            _queryParams.username = username;
        }

        if (password != null) {
            _queryParams.password = password;
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.JustinDouvilleApiEnvironment.Default,
                "user/auth/login",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as JustinDouvilleApi.UserAuthResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.JustinDouvilleApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.JustinDouvilleApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.JustinDouvilleApiTimeoutError("Timeout exceeded when calling GET /user/auth/login.");
            case "unknown":
                throw new errors.JustinDouvilleApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {UserClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.user.logoutUser()
     */
    public logoutUser(requestOptions?: UserClient.RequestOptions): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__logoutUser(requestOptions));
    }

    private async __logoutUser(requestOptions?: UserClient.RequestOptions): Promise<core.WithRawResponse<void>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.JustinDouvilleApiEnvironment.Default,
                "user/auth/logout",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.JustinDouvilleApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.JustinDouvilleApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.JustinDouvilleApiTimeoutError("Timeout exceeded when calling GET /user/auth/logout.");
            case "unknown":
                throw new errors.JustinDouvilleApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Retrieve user details using their username.
     *
     * @param {JustinDouvilleApi.GetUserByNameRequest} request
     * @param {UserClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.user.getUserByName({
     *         username: "username"
     *     })
     */
    public getUserByName(
        request: JustinDouvilleApi.GetUserByNameRequest,
        requestOptions?: UserClient.RequestOptions,
    ): core.HttpResponsePromise<JustinDouvilleApi.User> {
        return core.HttpResponsePromise.fromPromise(this.__getUserByName(request, requestOptions));
    }

    private async __getUserByName(
        request: JustinDouvilleApi.GetUserByNameRequest,
        requestOptions?: UserClient.RequestOptions,
    ): Promise<core.WithRawResponse<JustinDouvilleApi.User>> {
        const { username } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.JustinDouvilleApiEnvironment.Default,
                `user/${core.url.encodePathParam(username)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as JustinDouvilleApi.User, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.JustinDouvilleApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.JustinDouvilleApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.JustinDouvilleApiTimeoutError("Timeout exceeded when calling GET /user/{username}.");
            case "unknown":
                throw new errors.JustinDouvilleApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }
}
