// This file was auto-generated by Fern from our API Definition.

import { PlantClient } from "./api/resources/plant/client/Client.js";
import { UserClient } from "./api/resources/user/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "./BaseClient.js";

export declare namespace JustinDouvilleApiClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class JustinDouvilleApiClient {
    protected readonly _options: NormalizedClientOptions<JustinDouvilleApiClient.Options>;
    protected _plant: PlantClient | undefined;
    protected _user: UserClient | undefined;

    constructor(options: JustinDouvilleApiClient.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    public get plant(): PlantClient {
        return (this._plant ??= new PlantClient(this._options));
    }

    public get user(): UserClient {
        return (this._user ??= new UserClient(this._options));
    }
}
