// This file was auto-generated by Fern from our API Definition.

export const TheGreenRoomApiEnvironment = {
    Default: "https://api.plantstore.dev/v3",
} as const;

export type TheGreenRoomApiEnvironment = typeof TheGreenRoomApiEnvironment.Default;
