// This file was auto-generated by Fern from our API Definition.

export const JustinDouvilleApiEnvironment = {
    Default: "https://api.plantstore.dev/v3",
} as const;

export type JustinDouvilleApiEnvironment = typeof JustinDouvilleApiEnvironment.Default;
