// Code generated by Fern. DO NOT EDIT.

package user

import (
	context "context"
	sdk "sdk"
	core "sdk/core"
	internal "sdk/internal"
	option "sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (c *Client) LoginUser(
	ctx context.Context,
	request *sdk.LoginUserRequest,
	opts ...option.RequestOption,
) (*sdk.UserAuthResponse, error) {
	response, err := c.WithRawResponse.LoginUser(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) LogoutUser(
	ctx context.Context,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.LogoutUser(
		ctx,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Retrieve user details using their username.
func (c *Client) GetUserByName(
	ctx context.Context,
	request *sdk.GetUserByNameRequest,
	opts ...option.RequestOption,
) (*sdk.User, error) {
	response, err := c.WithRawResponse.GetUserByName(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
