# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .plant import Plant
    from .plant_created_payload import PlantCreatedPayload
    from .plant_created_payload_event import PlantCreatedPayloadEvent
    from .plant_response import PlantResponse
    from .plant_status import PlantStatus
    from .post_plant_updated_payload import PostPlantUpdatedPayload
    from .post_plant_updated_payload_event import PostPlantUpdatedPayloadEvent
    from .user import User
    from .user_auth_response import UserAuthResponse
    from .webhook_registration import WebhookRegistration
    from .webhook_registration_events_item import WebhookRegistrationEventsItem
    from .webhook_response import WebhookResponse
    from .webhook_response_status import WebhookResponseStatus
_dynamic_imports: typing.Dict[str, str] = {
    "Plant": ".plant",
    "PlantCreatedPayload": ".plant_created_payload",
    "PlantCreatedPayloadEvent": ".plant_created_payload_event",
    "PlantResponse": ".plant_response",
    "PlantStatus": ".plant_status",
    "PostPlantUpdatedPayload": ".post_plant_updated_payload",
    "PostPlantUpdatedPayloadEvent": ".post_plant_updated_payload_event",
    "User": ".user",
    "UserAuthResponse": ".user_auth_response",
    "WebhookRegistration": ".webhook_registration",
    "WebhookRegistrationEventsItem": ".webhook_registration_events_item",
    "WebhookResponse": ".webhook_response",
    "WebhookResponseStatus": ".webhook_response_status",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "Plant",
    "PlantCreatedPayload",
    "PlantCreatedPayloadEvent",
    "PlantResponse",
    "PlantStatus",
    "PostPlantUpdatedPayload",
    "PostPlantUpdatedPayloadEvent",
    "User",
    "UserAuthResponse",
    "WebhookRegistration",
    "WebhookRegistrationEventsItem",
    "WebhookResponse",
    "WebhookResponseStatus",
]
