# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .plant_created_payload_event import PlantCreatedPayloadEvent
from .plant_response import PlantResponse


class PlantCreatedPayload(UniversalBaseModel):
    event: typing.Optional[PlantCreatedPayloadEvent] = None
    timestamp: typing.Optional[dt.datetime] = None
    data: typing.Optional[PlantResponse] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
