# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .webhook_response_status import WebhookResponseStatus


class WebhookResponse(UniversalBaseModel):
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique identifier for the webhook
    """

    url: typing.Optional[str] = pydantic.Field(default=None)
    """
    The URL where webhook events are sent
    """

    events: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    List of subscribed events
    """

    status: typing.Optional[WebhookResponseStatus] = pydantic.Field(default=None)
    """
    Current status of the webhook
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
