# This file was auto-generated by Fern from our API Definition.

import typing

WebhookRegistrationEventsItem = typing.Union[
    typing.Literal["plant.created", "plant.updated", "plant.status_changed", "plant.deleted"], typing.Any
]
