# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .webhook_registration_events_item import WebhookRegistrationEventsItem


class WebhookRegistration(UniversalBaseModel):
    url: str = pydantic.Field()
    """
    The URL where webhook events will be sent
    """

    events: typing.List[WebhookRegistrationEventsItem] = pydantic.Field()
    """
    List of events to subscribe to
    """

    secret: typing.Optional[str] = pydantic.Field(default=None)
    """
    Secret used to sign webhook payloads
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
