/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.plant.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class SearchPlantsByStatusRequestStatus {
  public static final SearchPlantsByStatusRequestStatus AVAILABLE = new SearchPlantsByStatusRequestStatus(Value.AVAILABLE, "available");

  public static final SearchPlantsByStatusRequestStatus PENDING = new SearchPlantsByStatusRequestStatus(Value.PENDING, "pending");

  public static final SearchPlantsByStatusRequestStatus SOLD = new SearchPlantsByStatusRequestStatus(Value.SOLD, "sold");

  private final Value value;

  private final String string;

  SearchPlantsByStatusRequestStatus(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof SearchPlantsByStatusRequestStatus && this.string.equals(((SearchPlantsByStatusRequestStatus) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case AVAILABLE:
        return visitor.visitAvailable();
      case PENDING:
        return visitor.visitPending();
      case SOLD:
        return visitor.visitSold();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static SearchPlantsByStatusRequestStatus valueOf(String value) {
    switch (value) {
      case "available":
        return AVAILABLE;
      case "pending":
        return PENDING;
      case "sold":
        return SOLD;
      default:
        return new SearchPlantsByStatusRequestStatus(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    AVAILABLE,

    PENDING,

    SOLD,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitAvailable();

    T visitPending();

    T visitSold();

    T visitUnknown(String unknownType);
  }
}
