// This file was auto-generated by Fern from our API Definition.

export const SearchPlantsByStatusRequestStatus = {
    Available: "available",
    Pending: "pending",
    Sold: "sold",
} as const;
export type SearchPlantsByStatusRequestStatus =
    (typeof SearchPlantsByStatusRequestStatus)[keyof typeof SearchPlantsByStatusRequestStatus];
