// Code generated by Fern. DO NOT EDIT.

package api

import (
	core "sdk/core"
	internal "sdk/internal"
)

var ErrorCodes internal.ErrorCodes = internal.ErrorCodes{
	405: func(apiError *core.APIError) error {
		return &MethodNotAllowedError{
			APIError: apiError,
		}
	},
	400: func(apiError *core.APIError) error {
		return &BadRequestError{
			APIError: apiError,
		}
	},
	404: func(apiError *core.APIError) error {
		return &NotFoundError{
			APIError: apiError,
		}
	},
}
