/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.plant;

import core.ClientOptions;
import core.RequestOptions;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import resources.plant.requests.GetPlantByIdRequest;
import resources.plant.requests.SearchPlantsByStatusRequest;
import resources.plant.requests.SearchPlantsByTagsRequest;
import types.Plant;
import types.PlantResponse;

public class AsyncPlantClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawPlantClient rawClient;

  public AsyncPlantClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawPlantClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawPlantClient withRawResponse() {
    return this.rawClient;
  }

  public CompletableFuture<PlantResponse> addPlant() {
    return this.rawClient.addPlant().thenApply(response -> response.body());
  }

  public CompletableFuture<PlantResponse> addPlant(Plant request) {
    return this.rawClient.addPlant(request).thenApply(response -> response.body());
  }

  public CompletableFuture<PlantResponse> addPlant(Plant request, RequestOptions requestOptions) {
    return this.rawClient.addPlant(request, requestOptions).thenApply(response -> response.body());
  }

  public CompletableFuture<PlantResponse> updatePlant() {
    return this.rawClient.updatePlant().thenApply(response -> response.body());
  }

  public CompletableFuture<PlantResponse> updatePlant(Plant request) {
    return this.rawClient.updatePlant(request).thenApply(response -> response.body());
  }

  public CompletableFuture<PlantResponse> updatePlant(Plant request,
      RequestOptions requestOptions) {
    return this.rawClient.updatePlant(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Filter plants based on their current status.
   */
  public CompletableFuture<List<PlantResponse>> searchPlantsByStatus() {
    return this.rawClient.searchPlantsByStatus().thenApply(response -> response.body());
  }

  /**
   * Filter plants based on their current status.
   */
  public CompletableFuture<List<PlantResponse>> searchPlantsByStatus(
      SearchPlantsByStatusRequest request) {
    return this.rawClient.searchPlantsByStatus(request).thenApply(response -> response.body());
  }

  /**
   * Filter plants based on their current status.
   */
  public CompletableFuture<List<PlantResponse>> searchPlantsByStatus(
      SearchPlantsByStatusRequest request, RequestOptions requestOptions) {
    return this.rawClient.searchPlantsByStatus(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Filter plants based on associated tags.
   */
  public CompletableFuture<List<PlantResponse>> searchPlantsByTags() {
    return this.rawClient.searchPlantsByTags().thenApply(response -> response.body());
  }

  /**
   * Filter plants based on associated tags.
   */
  public CompletableFuture<List<PlantResponse>> searchPlantsByTags(
      SearchPlantsByTagsRequest request) {
    return this.rawClient.searchPlantsByTags(request).thenApply(response -> response.body());
  }

  /**
   * Filter plants based on associated tags.
   */
  public CompletableFuture<List<PlantResponse>> searchPlantsByTags(
      SearchPlantsByTagsRequest request, RequestOptions requestOptions) {
    return this.rawClient.searchPlantsByTags(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Retrieve a plant's details by its ID.
   */
  public CompletableFuture<PlantResponse> getPlantById(int plantId) {
    return this.rawClient.getPlantById(plantId).thenApply(response -> response.body());
  }

  /**
   * Retrieve a plant's details by its ID.
   */
  public CompletableFuture<PlantResponse> getPlantById(int plantId, GetPlantByIdRequest request) {
    return this.rawClient.getPlantById(plantId, request).thenApply(response -> response.body());
  }

  /**
   * Retrieve a plant's details by its ID.
   */
  public CompletableFuture<PlantResponse> getPlantById(int plantId, GetPlantByIdRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.getPlantById(plantId, request, requestOptions).thenApply(response -> response.body());
  }
}
