/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.plant;

import core.ClientOptions;
import core.RequestOptions;
import java.util.List;
import resources.plant.requests.GetPlantByIdRequest;
import resources.plant.requests.SearchPlantsByStatusRequest;
import resources.plant.requests.SearchPlantsByTagsRequest;
import types.Plant;
import types.PlantResponse;

public class PlantClient {
  protected final ClientOptions clientOptions;

  private final RawPlantClient rawClient;

  public PlantClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new RawPlantClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public RawPlantClient withRawResponse() {
    return this.rawClient;
  }

  public PlantResponse addPlant() {
    return this.rawClient.addPlant().body();
  }

  public PlantResponse addPlant(Plant request) {
    return this.rawClient.addPlant(request).body();
  }

  public PlantResponse addPlant(Plant request, RequestOptions requestOptions) {
    return this.rawClient.addPlant(request, requestOptions).body();
  }

  public PlantResponse updatePlant() {
    return this.rawClient.updatePlant().body();
  }

  public PlantResponse updatePlant(Plant request) {
    return this.rawClient.updatePlant(request).body();
  }

  public PlantResponse updatePlant(Plant request, RequestOptions requestOptions) {
    return this.rawClient.updatePlant(request, requestOptions).body();
  }

  /**
   * Filter plants based on their current status.
   */
  public List<PlantResponse> searchPlantsByStatus() {
    return this.rawClient.searchPlantsByStatus().body();
  }

  /**
   * Filter plants based on their current status.
   */
  public List<PlantResponse> searchPlantsByStatus(SearchPlantsByStatusRequest request) {
    return this.rawClient.searchPlantsByStatus(request).body();
  }

  /**
   * Filter plants based on their current status.
   */
  public List<PlantResponse> searchPlantsByStatus(SearchPlantsByStatusRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.searchPlantsByStatus(request, requestOptions).body();
  }

  /**
   * Filter plants based on associated tags.
   */
  public List<PlantResponse> searchPlantsByTags() {
    return this.rawClient.searchPlantsByTags().body();
  }

  /**
   * Filter plants based on associated tags.
   */
  public List<PlantResponse> searchPlantsByTags(SearchPlantsByTagsRequest request) {
    return this.rawClient.searchPlantsByTags(request).body();
  }

  /**
   * Filter plants based on associated tags.
   */
  public List<PlantResponse> searchPlantsByTags(SearchPlantsByTagsRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.searchPlantsByTags(request, requestOptions).body();
  }

  /**
   * Retrieve a plant's details by its ID.
   */
  public PlantResponse getPlantById(int plantId) {
    return this.rawClient.getPlantById(plantId).body();
  }

  /**
   * Retrieve a plant's details by its ID.
   */
  public PlantResponse getPlantById(int plantId, GetPlantByIdRequest request) {
    return this.rawClient.getPlantById(plantId, request).body();
  }

  /**
   * Retrieve a plant's details by its ID.
   */
  public PlantResponse getPlantById(int plantId, GetPlantByIdRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.getPlantById(plantId, request, requestOptions).body();
  }
}
