/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.plant;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import core.ClientOptions;
import core.JustinDouvilleApiApiException;
import core.JustinDouvilleApiException;
import core.JustinDouvilleApiHttpResponse;
import core.MediaTypes;
import core.ObjectMappers;
import core.QueryStringMapper;
import core.RequestOptions;
import errors.BadRequestError;
import errors.MethodNotAllowedError;
import errors.NotFoundError;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.List;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import resources.plant.requests.GetPlantByIdRequest;
import resources.plant.requests.SearchPlantsByStatusRequest;
import resources.plant.requests.SearchPlantsByTagsRequest;
import types.Plant;
import types.PlantResponse;

public class RawPlantClient {
  protected final ClientOptions clientOptions;

  public RawPlantClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  public JustinDouvilleApiHttpResponse<PlantResponse> addPlant() {
    return addPlant(Plant.builder().build());
  }

  public JustinDouvilleApiHttpResponse<PlantResponse> addPlant(Plant request) {
    return addPlant(request,null);
  }

  public JustinDouvilleApiHttpResponse<PlantResponse> addPlant(Plant request,
      RequestOptions requestOptions) {
    HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("plant")
      .build();
    RequestBody body;
    try {
      body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
    }
    catch(JsonProcessingException e) {
      throw new JustinDouvilleApiException("Failed to serialize request", e);
    }
    Request okhttpRequest = new Request.Builder()
      .url(httpUrl)
      .method("POST", body)
      .headers(Headers.of(clientOptions.headers(requestOptions)))
      .addHeader("Content-Type", "application/json")
      .addHeader("Accept", "application/json")
      .build();
    OkHttpClient client = clientOptions.httpClient();
    if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
      client = clientOptions.httpClientWithTimeout(requestOptions);
    }
    try (Response response = client.newCall(okhttpRequest).execute()) {
      ResponseBody responseBody = response.body();
      String responseBodyString = responseBody != null ? responseBody.string() : "{}";
      if (response.isSuccessful()) {
        return new JustinDouvilleApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, PlantResponse.class), response);
      }
      try {
        if (response.code() == 405) {
          throw new MethodNotAllowedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
        }
      }
      catch (JsonProcessingException ignored) {
        // unable to map error response, throwing generic error
      }
      Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
      throw new JustinDouvilleApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
    }
    catch (IOException e) {
      throw new JustinDouvilleApiException("Network error executing HTTP request", e);
    }
  }

  public JustinDouvilleApiHttpResponse<PlantResponse> updatePlant() {
    return updatePlant(Plant.builder().build());
  }

  public JustinDouvilleApiHttpResponse<PlantResponse> updatePlant(Plant request) {
    return updatePlant(request,null);
  }

  public JustinDouvilleApiHttpResponse<PlantResponse> updatePlant(Plant request,
      RequestOptions requestOptions) {
    HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("plant")
      .build();
    RequestBody body;
    try {
      body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
    }
    catch(JsonProcessingException e) {
      throw new JustinDouvilleApiException("Failed to serialize request", e);
    }
    Request okhttpRequest = new Request.Builder()
      .url(httpUrl)
      .method("PUT", body)
      .headers(Headers.of(clientOptions.headers(requestOptions)))
      .addHeader("Content-Type", "application/json")
      .addHeader("Accept", "application/json")
      .build();
    OkHttpClient client = clientOptions.httpClient();
    if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
      client = clientOptions.httpClientWithTimeout(requestOptions);
    }
    try (Response response = client.newCall(okhttpRequest).execute()) {
      ResponseBody responseBody = response.body();
      String responseBodyString = responseBody != null ? responseBody.string() : "{}";
      if (response.isSuccessful()) {
        return new JustinDouvilleApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, PlantResponse.class), response);
      }
      try {
        switch (response.code()) {
          case 400:throw new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
          case 404:throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
        }
      }
      catch (JsonProcessingException ignored) {
        // unable to map error response, throwing generic error
      }
      Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
      throw new JustinDouvilleApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
    }
    catch (IOException e) {
      throw new JustinDouvilleApiException("Network error executing HTTP request", e);
    }
  }

  /**
   * Filter plants based on their current status.
   */
  public JustinDouvilleApiHttpResponse<List<PlantResponse>> searchPlantsByStatus() {
    return searchPlantsByStatus(SearchPlantsByStatusRequest.builder().build());
  }

  /**
   * Filter plants based on their current status.
   */
  public JustinDouvilleApiHttpResponse<List<PlantResponse>> searchPlantsByStatus(
      SearchPlantsByStatusRequest request) {
    return searchPlantsByStatus(request,null);
  }

  /**
   * Filter plants based on their current status.
   */
  public JustinDouvilleApiHttpResponse<List<PlantResponse>> searchPlantsByStatus(
      SearchPlantsByStatusRequest request, RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("plant/search/status");if (request.getStatus().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "status", request.getStatus().get(), false);
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      try (Response response = client.newCall(okhttpRequest).execute()) {
        ResponseBody responseBody = response.body();
        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
        if (response.isSuccessful()) {
          return new JustinDouvilleApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, new TypeReference<List<PlantResponse>>() {}), response);
        }
        Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
        throw new JustinDouvilleApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
      }
      catch (IOException e) {
        throw new JustinDouvilleApiException("Network error executing HTTP request", e);
      }
    }

    /**
     * Filter plants based on associated tags.
     */
    public JustinDouvilleApiHttpResponse<List<PlantResponse>> searchPlantsByTags() {
      return searchPlantsByTags(SearchPlantsByTagsRequest.builder().build());
    }

    /**
     * Filter plants based on associated tags.
     */
    public JustinDouvilleApiHttpResponse<List<PlantResponse>> searchPlantsByTags(
        SearchPlantsByTagsRequest request) {
      return searchPlantsByTags(request,null);
    }

    /**
     * Filter plants based on associated tags.
     */
    public JustinDouvilleApiHttpResponse<List<PlantResponse>> searchPlantsByTags(
        SearchPlantsByTagsRequest request, RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("plant/search/tags");if (request.getTags().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "tags", request.getTags().get(), true);
        }
        Request.Builder _requestBuilder = new Request.Builder()
          .url(httpUrl.build())
          .method("GET", null)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
          ResponseBody responseBody = response.body();
          String responseBodyString = responseBody != null ? responseBody.string() : "{}";
          if (response.isSuccessful()) {
            return new JustinDouvilleApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, new TypeReference<List<PlantResponse>>() {}), response);
          }
          Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
          throw new JustinDouvilleApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
        }
        catch (IOException e) {
          throw new JustinDouvilleApiException("Network error executing HTTP request", e);
        }
      }

      /**
       * Retrieve a plant's details by its ID.
       */
      public JustinDouvilleApiHttpResponse<PlantResponse> getPlantById(int plantId) {
        return getPlantById(plantId,GetPlantByIdRequest.builder().build());
      }

      /**
       * Retrieve a plant's details by its ID.
       */
      public JustinDouvilleApiHttpResponse<PlantResponse> getPlantById(int plantId,
          GetPlantByIdRequest request) {
        return getPlantById(plantId,request,null);
      }

      /**
       * Retrieve a plant's details by its ID.
       */
      public JustinDouvilleApiHttpResponse<PlantResponse> getPlantById(int plantId,
          GetPlantByIdRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

          .addPathSegments("plant")
          .addPathSegment(Integer.toString(plantId))
          .build();
        Request.Builder _requestBuilder = new Request.Builder()
          .url(httpUrl)
          .method("GET", null)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
          ResponseBody responseBody = response.body();
          String responseBodyString = responseBody != null ? responseBody.string() : "{}";
          if (response.isSuccessful()) {
            return new JustinDouvilleApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, PlantResponse.class), response);
          }
          Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
          throw new JustinDouvilleApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
        }
        catch (IOException e) {
          throw new JustinDouvilleApiException("Network error executing HTTP request", e);
        }
      }
    }
