// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import * as JustinDouvilleApi from "../../../index.js";

export declare namespace PlantClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Everything about your Plants
 */
export class PlantClient {
    protected readonly _options: NormalizedClientOptions<PlantClient.Options>;

    constructor(options: PlantClient.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * @param {JustinDouvilleApi.Plant} request
     * @param {PlantClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link JustinDouvilleApi.MethodNotAllowedError}
     *
     * @example
     *     await client.plant.addPlant({
     *         name: "Fern",
     *         category: "Indoor",
     *         tags: ["green", "leafy"],
     *         status: "available"
     *     })
     */
    public addPlant(
        request: JustinDouvilleApi.Plant,
        requestOptions?: PlantClient.RequestOptions,
    ): core.HttpResponsePromise<JustinDouvilleApi.PlantResponse> {
        return core.HttpResponsePromise.fromPromise(this.__addPlant(request, requestOptions));
    }

    private async __addPlant(
        request: JustinDouvilleApi.Plant,
        requestOptions?: PlantClient.RequestOptions,
    ): Promise<core.WithRawResponse<JustinDouvilleApi.PlantResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.JustinDouvilleApiEnvironment.Default,
                "plant",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as JustinDouvilleApi.PlantResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 405:
                    throw new JustinDouvilleApi.MethodNotAllowedError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.JustinDouvilleApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.JustinDouvilleApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.JustinDouvilleApiTimeoutError("Timeout exceeded when calling POST /plant.");
            case "unknown":
                throw new errors.JustinDouvilleApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {JustinDouvilleApi.Plant} request
     * @param {PlantClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link JustinDouvilleApi.BadRequestError}
     * @throws {@link JustinDouvilleApi.NotFoundError}
     *
     * @example
     *     await client.plant.updatePlant({
     *         name: "Fern",
     *         category: "Indoor",
     *         tags: ["green", "leafy"],
     *         status: "sold"
     *     })
     */
    public updatePlant(
        request: JustinDouvilleApi.Plant,
        requestOptions?: PlantClient.RequestOptions,
    ): core.HttpResponsePromise<JustinDouvilleApi.PlantResponse> {
        return core.HttpResponsePromise.fromPromise(this.__updatePlant(request, requestOptions));
    }

    private async __updatePlant(
        request: JustinDouvilleApi.Plant,
        requestOptions?: PlantClient.RequestOptions,
    ): Promise<core.WithRawResponse<JustinDouvilleApi.PlantResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.JustinDouvilleApiEnvironment.Default,
                "plant",
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as JustinDouvilleApi.PlantResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new JustinDouvilleApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new JustinDouvilleApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.JustinDouvilleApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.JustinDouvilleApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.JustinDouvilleApiTimeoutError("Timeout exceeded when calling PUT /plant.");
            case "unknown":
                throw new errors.JustinDouvilleApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Filter plants based on their current status.
     *
     * @param {JustinDouvilleApi.SearchPlantsByStatusRequest} request
     * @param {PlantClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.plant.searchPlantsByStatus()
     */
    public searchPlantsByStatus(
        request: JustinDouvilleApi.SearchPlantsByStatusRequest = {},
        requestOptions?: PlantClient.RequestOptions,
    ): core.HttpResponsePromise<JustinDouvilleApi.PlantResponse[]> {
        return core.HttpResponsePromise.fromPromise(this.__searchPlantsByStatus(request, requestOptions));
    }

    private async __searchPlantsByStatus(
        request: JustinDouvilleApi.SearchPlantsByStatusRequest = {},
        requestOptions?: PlantClient.RequestOptions,
    ): Promise<core.WithRawResponse<JustinDouvilleApi.PlantResponse[]>> {
        const { status } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (status != null) {
            _queryParams.status = status;
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.JustinDouvilleApiEnvironment.Default,
                "plant/search/status",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as JustinDouvilleApi.PlantResponse[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.JustinDouvilleApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.JustinDouvilleApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.JustinDouvilleApiTimeoutError(
                    "Timeout exceeded when calling GET /plant/search/status.",
                );
            case "unknown":
                throw new errors.JustinDouvilleApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Filter plants based on associated tags.
     *
     * @param {JustinDouvilleApi.SearchPlantsByTagsRequest} request
     * @param {PlantClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.plant.searchPlantsByTags()
     */
    public searchPlantsByTags(
        request: JustinDouvilleApi.SearchPlantsByTagsRequest = {},
        requestOptions?: PlantClient.RequestOptions,
    ): core.HttpResponsePromise<JustinDouvilleApi.PlantResponse[]> {
        return core.HttpResponsePromise.fromPromise(this.__searchPlantsByTags(request, requestOptions));
    }

    private async __searchPlantsByTags(
        request: JustinDouvilleApi.SearchPlantsByTagsRequest = {},
        requestOptions?: PlantClient.RequestOptions,
    ): Promise<core.WithRawResponse<JustinDouvilleApi.PlantResponse[]>> {
        const { tags } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (tags != null) {
            if (Array.isArray(tags)) {
                _queryParams.tags = tags.map((item) => item);
            } else {
                _queryParams.tags = tags;
            }
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.JustinDouvilleApiEnvironment.Default,
                "plant/search/tags",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as JustinDouvilleApi.PlantResponse[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.JustinDouvilleApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.JustinDouvilleApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.JustinDouvilleApiTimeoutError("Timeout exceeded when calling GET /plant/search/tags.");
            case "unknown":
                throw new errors.JustinDouvilleApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Retrieve a plant's details by its ID.
     *
     * @param {JustinDouvilleApi.GetPlantByIdRequest} request
     * @param {PlantClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.plant.getPlantById({
     *         plantId: 1
     *     })
     */
    public getPlantById(
        request: JustinDouvilleApi.GetPlantByIdRequest,
        requestOptions?: PlantClient.RequestOptions,
    ): core.HttpResponsePromise<JustinDouvilleApi.PlantResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getPlantById(request, requestOptions));
    }

    private async __getPlantById(
        request: JustinDouvilleApi.GetPlantByIdRequest,
        requestOptions?: PlantClient.RequestOptions,
    ): Promise<core.WithRawResponse<JustinDouvilleApi.PlantResponse>> {
        const { plantId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.JustinDouvilleApiEnvironment.Default,
                `plant/${core.url.encodePathParam(plantId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as JustinDouvilleApi.PlantResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.JustinDouvilleApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.JustinDouvilleApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.JustinDouvilleApiTimeoutError("Timeout exceeded when calling GET /plant/{plantId}.");
            case "unknown":
                throw new errors.JustinDouvilleApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }
}
