/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.user;

import core.ClientOptions;
import core.JustinDouvilleApiApiException;
import core.JustinDouvilleApiException;
import core.JustinDouvilleApiHttpResponse;
import core.ObjectMappers;
import core.QueryStringMapper;
import core.RequestOptions;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.Void;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;
import resources.user.requests.GetUserByNameRequest;
import resources.user.requests.LoginUserRequest;
import types.User;
import types.UserAuthResponse;

public class AsyncRawUserClient {
  protected final ClientOptions clientOptions;

  public AsyncRawUserClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  public CompletableFuture<JustinDouvilleApiHttpResponse<UserAuthResponse>> loginUser() {
    return loginUser(LoginUserRequest.builder().build());
  }

  public CompletableFuture<JustinDouvilleApiHttpResponse<UserAuthResponse>> loginUser(
      LoginUserRequest request) {
    return loginUser(request,null);
  }

  public CompletableFuture<JustinDouvilleApiHttpResponse<UserAuthResponse>> loginUser(
      LoginUserRequest request, RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("user/auth/login");if (request.getUsername().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "username", request.getUsername().get(), false);
      }
      if (request.getPassword().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "password", request.getPassword().get(), false);
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      CompletableFuture<JustinDouvilleApiHttpResponse<UserAuthResponse>> future = new CompletableFuture<>();
      client.newCall(okhttpRequest).enqueue(new Callback() {
        @Override
        public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
          try (ResponseBody responseBody = response.body()) {
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
              future.complete(new JustinDouvilleApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, UserAuthResponse.class), response));
              return;
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            future.completeExceptionally(new JustinDouvilleApiApiException("Error with status code " + response.code(), response.code(), errorBody, response));
            return;
          }
          catch (IOException e) {
            future.completeExceptionally(new JustinDouvilleApiException("Network error executing HTTP request", e));
          }
        }

        @Override
        public void onFailure(@NotNull Call call, @NotNull IOException e) {
          future.completeExceptionally(new JustinDouvilleApiException("Network error executing HTTP request", e));
        }
      });
      return future;
    }

    public CompletableFuture<JustinDouvilleApiHttpResponse<Void>> logoutUser() {
      return logoutUser(null);
    }

    public CompletableFuture<JustinDouvilleApiHttpResponse<Void>> logoutUser(
        RequestOptions requestOptions) {
      HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("user/auth/logout")
        .build();
      Request okhttpRequest = new Request.Builder()
        .url(httpUrl)
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      CompletableFuture<JustinDouvilleApiHttpResponse<Void>> future = new CompletableFuture<>();
      client.newCall(okhttpRequest).enqueue(new Callback() {
        @Override
        public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
          try (ResponseBody responseBody = response.body()) {
            if (response.isSuccessful()) {
              future.complete(new JustinDouvilleApiHttpResponse<>(null, response));
              return;
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            future.completeExceptionally(new JustinDouvilleApiApiException("Error with status code " + response.code(), response.code(), errorBody, response));
            return;
          }
          catch (IOException e) {
            future.completeExceptionally(new JustinDouvilleApiException("Network error executing HTTP request", e));
          }
        }

        @Override
        public void onFailure(@NotNull Call call, @NotNull IOException e) {
          future.completeExceptionally(new JustinDouvilleApiException("Network error executing HTTP request", e));
        }
      });
      return future;
    }

    /**
     * Retrieve user details using their username.
     */
    public CompletableFuture<JustinDouvilleApiHttpResponse<User>> getUserByName(String username) {
      return getUserByName(username,GetUserByNameRequest.builder().build());
    }

    /**
     * Retrieve user details using their username.
     */
    public CompletableFuture<JustinDouvilleApiHttpResponse<User>> getUserByName(String username,
        GetUserByNameRequest request) {
      return getUserByName(username,request,null);
    }

    /**
     * Retrieve user details using their username.
     */
    public CompletableFuture<JustinDouvilleApiHttpResponse<User>> getUserByName(String username,
        GetUserByNameRequest request, RequestOptions requestOptions) {
      HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("user")
        .addPathSegment(username)
        .build();
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl)
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      CompletableFuture<JustinDouvilleApiHttpResponse<User>> future = new CompletableFuture<>();
      client.newCall(okhttpRequest).enqueue(new Callback() {
        @Override
        public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
          try (ResponseBody responseBody = response.body()) {
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
              future.complete(new JustinDouvilleApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, User.class), response));
              return;
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            future.completeExceptionally(new JustinDouvilleApiApiException("Error with status code " + response.code(), response.code(), errorBody, response));
            return;
          }
          catch (IOException e) {
            future.completeExceptionally(new JustinDouvilleApiException("Network error executing HTTP request", e));
          }
        }

        @Override
        public void onFailure(@NotNull Call call, @NotNull IOException e) {
          future.completeExceptionally(new JustinDouvilleApiException("Network error executing HTTP request", e));
        }
      });
      return future;
    }
  }
