/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.user;

import core.ClientOptions;
import core.RequestOptions;
import java.lang.String;
import java.lang.Void;
import java.util.concurrent.CompletableFuture;
import resources.user.requests.GetUserByNameRequest;
import resources.user.requests.LoginUserRequest;
import types.User;
import types.UserAuthResponse;

public class AsyncUserClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawUserClient rawClient;

  public AsyncUserClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawUserClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawUserClient withRawResponse() {
    return this.rawClient;
  }

  public CompletableFuture<UserAuthResponse> loginUser() {
    return this.rawClient.loginUser().thenApply(response -> response.body());
  }

  public CompletableFuture<UserAuthResponse> loginUser(LoginUserRequest request) {
    return this.rawClient.loginUser(request).thenApply(response -> response.body());
  }

  public CompletableFuture<UserAuthResponse> loginUser(LoginUserRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.loginUser(request, requestOptions).thenApply(response -> response.body());
  }

  public CompletableFuture<Void> logoutUser() {
    return this.rawClient.logoutUser().thenApply(response -> response.body());
  }

  public CompletableFuture<Void> logoutUser(RequestOptions requestOptions) {
    return this.rawClient.logoutUser(requestOptions).thenApply(response -> response.body());
  }

  /**
   * Retrieve user details using their username.
   */
  public CompletableFuture<User> getUserByName(String username) {
    return this.rawClient.getUserByName(username).thenApply(response -> response.body());
  }

  /**
   * Retrieve user details using their username.
   */
  public CompletableFuture<User> getUserByName(String username, GetUserByNameRequest request) {
    return this.rawClient.getUserByName(username, request).thenApply(response -> response.body());
  }

  /**
   * Retrieve user details using their username.
   */
  public CompletableFuture<User> getUserByName(String username, GetUserByNameRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.getUserByName(username, request, requestOptions).thenApply(response -> response.body());
  }
}
