/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.user;

import core.ClientOptions;
import core.JustinDouvilleApiApiException;
import core.JustinDouvilleApiException;
import core.JustinDouvilleApiHttpResponse;
import core.ObjectMappers;
import core.QueryStringMapper;
import core.RequestOptions;
import java.io.IOException;
import java.lang.Object;
import java.lang.String;
import java.lang.Void;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;
import resources.user.requests.GetUserByNameRequest;
import resources.user.requests.LoginUserRequest;
import types.User;
import types.UserAuthResponse;

public class RawUserClient {
  protected final ClientOptions clientOptions;

  public RawUserClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  public JustinDouvilleApiHttpResponse<UserAuthResponse> loginUser() {
    return loginUser(LoginUserRequest.builder().build());
  }

  public JustinDouvilleApiHttpResponse<UserAuthResponse> loginUser(LoginUserRequest request) {
    return loginUser(request,null);
  }

  public JustinDouvilleApiHttpResponse<UserAuthResponse> loginUser(LoginUserRequest request,
      RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("user/auth/login");if (request.getUsername().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "username", request.getUsername().get(), false);
      }
      if (request.getPassword().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "password", request.getPassword().get(), false);
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      try (Response response = client.newCall(okhttpRequest).execute()) {
        ResponseBody responseBody = response.body();
        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
        if (response.isSuccessful()) {
          return new JustinDouvilleApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, UserAuthResponse.class), response);
        }
        Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
        throw new JustinDouvilleApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
      }
      catch (IOException e) {
        throw new JustinDouvilleApiException("Network error executing HTTP request", e);
      }
    }

    public JustinDouvilleApiHttpResponse<Void> logoutUser() {
      return logoutUser(null);
    }

    public JustinDouvilleApiHttpResponse<Void> logoutUser(RequestOptions requestOptions) {
      HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("user/auth/logout")
        .build();
      Request okhttpRequest = new Request.Builder()
        .url(httpUrl)
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      try (Response response = client.newCall(okhttpRequest).execute()) {
        ResponseBody responseBody = response.body();
        if (response.isSuccessful()) {
          return new JustinDouvilleApiHttpResponse<>(null, response);
        }
        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
        Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
        throw new JustinDouvilleApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
      }
      catch (IOException e) {
        throw new JustinDouvilleApiException("Network error executing HTTP request", e);
      }
    }

    /**
     * Retrieve user details using their username.
     */
    public JustinDouvilleApiHttpResponse<User> getUserByName(String username) {
      return getUserByName(username,GetUserByNameRequest.builder().build());
    }

    /**
     * Retrieve user details using their username.
     */
    public JustinDouvilleApiHttpResponse<User> getUserByName(String username,
        GetUserByNameRequest request) {
      return getUserByName(username,request,null);
    }

    /**
     * Retrieve user details using their username.
     */
    public JustinDouvilleApiHttpResponse<User> getUserByName(String username,
        GetUserByNameRequest request, RequestOptions requestOptions) {
      HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("user")
        .addPathSegment(username)
        .build();
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl)
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      try (Response response = client.newCall(okhttpRequest).execute()) {
        ResponseBody responseBody = response.body();
        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
        if (response.isSuccessful()) {
          return new JustinDouvilleApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, User.class), response);
        }
        Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
        throw new JustinDouvilleApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
      }
      catch (IOException e) {
        throw new JustinDouvilleApiException("Network error executing HTTP request", e);
      }
    }
  }
