/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.user;

import core.ClientOptions;
import core.RequestOptions;
import java.lang.String;
import resources.user.requests.GetUserByNameRequest;
import resources.user.requests.LoginUserRequest;
import types.User;
import types.UserAuthResponse;

public class UserClient {
  protected final ClientOptions clientOptions;

  private final RawUserClient rawClient;

  public UserClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new RawUserClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public RawUserClient withRawResponse() {
    return this.rawClient;
  }

  public UserAuthResponse loginUser() {
    return this.rawClient.loginUser().body();
  }

  public UserAuthResponse loginUser(LoginUserRequest request) {
    return this.rawClient.loginUser(request).body();
  }

  public UserAuthResponse loginUser(LoginUserRequest request, RequestOptions requestOptions) {
    return this.rawClient.loginUser(request, requestOptions).body();
  }

  public void logoutUser() {
    this.rawClient.logoutUser().body();
  }

  public void logoutUser(RequestOptions requestOptions) {
    this.rawClient.logoutUser(requestOptions).body();
  }

  /**
   * Retrieve user details using their username.
   */
  public User getUserByName(String username) {
    return this.rawClient.getUserByName(username).body();
  }

  /**
   * Retrieve user details using their username.
   */
  public User getUserByName(String username, GetUserByNameRequest request) {
    return this.rawClient.getUserByName(username, request).body();
  }

  /**
   * Retrieve user details using their username.
   */
  public User getUserByName(String username, GetUserByNameRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.getUserByName(username, request, requestOptions).body();
  }
}
